version: '3'
services:
  postgres:
    container_name: xingyu-postgres
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - xingyu-network

  web:
    image: xingyuji/addressbook:latest
    container_name: addressbook
    hostname: addressbook
    ports:
      - 8080:8080
    volumes:
      - ./web/data_dir:/addressbook/data_dir
      - ./web/logs:/addressbook/logs
    restart: unless-stopped
    links:
      - postgres:postgres
    networks:
      - xingyu-network
networks:
  xingyu-network: