spring:
  application:
    name: AddressBook
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: postgres
    password: 123456
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false

server:
  port: 8080